srcfiles = [
            'announce.cc',
        ]

import os

def build(ctx):
    print('→ build from ' + ctx.path.abspath())

    ctx(features='subst',
            source='build_version.h.in',
            target='build_version.h',
            VERSION = ctx.env['VERSION'],
            )

    ctx.program(source=srcfiles,
            target='mdns-announce',
            use=['LIBEV', 'LIBDNS_SD'],
            includes=['.'],
            )

def configure(cfg):
    pass
